FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY service-a ./service-a

RUN CGO_ENABLED=0 go build -o /service-a ./service-a

FROM alpine:3.20

COPY --from=builder /service-a /service-a

CMD ["/service-a"]
