FROM mcr.microsoft.com/dotnet/sdk:8.0 AS builder

WORKDIR /src

COPY service-a/service-a.csproj ./service-a/
RUN dotnet restore service-a/service-a.csproj

COPY service-a ./service-a
RUN dotnet publish service-a/service-a.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app
COPY --from=builder /app ./

ENTRYPOINT ["dotnet", "service-a.dll"]
