<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>fga-opa-api</AssemblyName>
    <RootNamespace>FgaOpaApi</RootNamespace>
  </PropertyGroup>

</Project>
