FROM maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY service-b/pom.xml ./
RUN mvn -q dependency:go-offline

COPY service-b/src ./src
RUN mvn -q clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine

WORKDIR /app
COPY --from=builder /app/target/service-b.jar ./app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
